steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'quickstart-image:tag1', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'quickstart-image:tag1']
options:
  logging: CLOUD_LOGGING_ONLY

