steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/rational-axe-453306-s4/my-faiz-repo-for-docker', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/rational-axe-453306-s4/my-faiz-repo-for-docker']

options:
  logging: CLOUD_LOGGING_ONLY

